### ISSUE TITLE
WNT Question

### ISSUE THREAD

**Issue by JJanAA** [wirepas/evk#4]
In the WNT under: Settings/Networks we have application data. In the help tab it is referred to Dual-MCU Api doc. WP_RM-100. Where do I find it?

**Comment by PFigs** [comment]
Hi!

The application data format is specified in the application note provided to you under share file. It consists of about a certain amount of bytes which are propagated to the nodes once they attach to the network.

The document WP-RM-100 is currently only available for licensees.

**Comment by JJanAA** [comment]
Thanks!

**Comment by JJanAA** [comment]
Regarding Application data in Settings, is it here I can apply new configuration to the Ruuvi tags? I am thinking on changing the reporting interval or enable/disable sensors. I have read Ruuvi-application_note.PDF and i have the appconfig_helper. But I need some description or documentation on how to get this settings to the Ruuvi tag.

**Comment by PFigs** [comment]
Hi!

The appconfig helper will give you the payload which you need to copy in our WNT tool. The script reads a yaml file where you can specify which sensors are to be enabled and the reporting interval.

Here's an example on how to enable the accelerometer sensors with an interval rate of 300 seconds:

```yaml
---
#Wirepas Oy 2019

version: 1
commands:

  enable_sensors:
    type: 1
    length: 6
    fields:
      temperature_enable: 0
      humidity_enable: 0
      presure_enable: 0
      accel_x_enable: 1
      accel_y_enable: 1
      accel_z_enable: 1
    format: '<BBBBBBBB'

  update_rate:
    type: 2
    length: 2
    fields:
      interval: 300
    format: '<BBH'
```
Copying the payload generated by the helper into WNT will push the configuration to the WM network, thus trigger the application reconfiguration.

WNT's user guide is available in sharefile but for your reference here are the steps to follow:

1. Open WNT
2. Connect with the given credentials
3. On the left icons, click on settings
4. Click on neworks
5. Copy paste the payload generated by the python script into the application data field
6. Press apply network
7. Changes will be propagated to the network and connected devices

Let me know if something is unclear.

Have a good day :sparkles:
